import type { Config } from "tailwindcss";

// generated by fullstack-pro-max -- palette UX088 (Near-Black SaaS Dark), pairing UX098
export default {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        base: "#0B0B0E",
        surface: "#131318",
        ink: "#E7E7EA",
        accent: "#5E6AD2",
      },
      fontFamily: {
        display: ["var(--font-display)"],
        body: ["var(--font-body)"],
      },
      borderRadius: { sm: "4px", DEFAULT: "8px", lg: "16px" },
      boxShadow: { raised: "0 1px 2px rgb(0 0 0 / 0.06)", lifted: "0 2px 8px rgb(0 0 0 / 0.08)" },
      transitionDuration: { fast: "120ms", base: "200ms", slow: "400ms" },
      transitionTimingFunction: { out: "cubic-bezier(0.16, 1, 0.3, 1)" },
    },
  },
  plugins: [],
} satisfies Config;
